model:
    arch: rcnn3
data:
    dataset: road
    train_split: train
    val_split: valid
    test_split: test
    void_class: 2
    img_rows: "same"
    img_cols: "same"
    path: /cvlabdata2/home/user/data/toronto
training:
    train_iters: 60000
    batch_size: 2
    validate_batch_size: 1
    val_interval: 500
    n_workers: 4
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-3
        weight_decay: 0.0005
        momentum: 0.9
    loss:
        name: 'multi_step_cross_entropy'
        reduction: 'sum'
        scale_weight: 0.4
    lr_schedule:
        name: 'StepLR'
        lr_decay_step_size: 1800
        lr_decay_factor_gamma: 0.5
    resume: best.pkl
